steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "gcr.io/$PROJECT_ID/hacktech-deploy:$COMMIT_SHA",
              "./client",
              "--build-arg",
              "CLIENT_ID=${_CLIENT_ID}",
              "--build-arg",
              "REDIRECT_URI=${_REDIRECT_URI}",
          ]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/hacktech-deploy:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          [
              "run",
              "deploy",
              "hacktech-deploy",
              "--image",
              "gcr.io/$PROJECT_ID/hacktech-deploy:$COMMIT_SHA",
              "--region",
              "europe-west4",
          ]
options:
    logging: CLOUD_LOGGING_ONLY
images:
    - gcr.io/$PROJECT_ID/hacktech-deploy:$COMMIT_SHA
